config/routes.rb
Rails.application.routes.draw do
  
  resources :tickets do
	collection do
		get :getAdmins
  	end
  end

  devise_for :admins
  devise_for :users

  root 'pages#index'

  resources :pages do
	collection do
		get :admin
		get :getAllUsers
		get :index
  	end
  end

 

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/controller.rb
class Controller < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

	self.table_name = "tickets"

	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :tickets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_paramters, if: :devise_controller?

  protected

  def configure_permitted_paramters
	devise_parameter_sanitizer.for(:account_update) << :name
	devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	


	def getAllUsers

		@users = User.order(:id).all

		respond_to do |format|
			format.html
			format.xml { render :xml => @users }
		end

	end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
   if current_user.admin?
	@user = current_user.id
	@tickets = Ticket.where("status = ? and (user_id = ? or user_id is ?)", "false", @user, nil).all
   end

   if !current_user.admin?
	    @user = current_user.id
	    @tickets = Ticket.where("status = ? and created_id = ?", "false", @user).all
   end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
	
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
   #gets the current user id from who the ticket belongs to
    @user = current_user.id
   #Gets the tickt info from the params and parses the desired information
    @ticketInfo = ticket_params
    @title = @ticketInfo["title"]
    @body = @ticketInfo["body"]
    @level = @ticketInfo["level"]
    @assigned_to = @ticketInfo["assigned_to"]
   #Attempts to create new ticket
    @ticket = Ticket.new(:title => @title.to_s, :body => @body.to_s, :level => @level, :user_id => @assigned_to, :created_id => @user)
    

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getAdmins

	@admins = User.where("admin = ?", "true").all.pluck(:name, :id).join(', ')

	puts @admins

	respond_to do |format|
		format.json { render json: { 'admins': @admins } }
	end	
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :body, :level, :user_id, :assigned_to, :status, :created_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def header(text)
  content_for(:header) { text.to_s }
end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tickets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Devise Demo', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
	<% if user_signed_in? %>
		<li><%= link_to "Tickets", tickets_path %></li>
	<% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %>
		<span class="caret">
		</span>
	      </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
		<% if current_user.admin? %>
			<li><%= link_to 'Admin Settings', 'pages/admin' %></li>
		<% else %>

		<% end %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>




</body>
</html>

app/views/pages/admin.html.erb
<%= link_to "Users", 'getAllUsers' %>

app/views/pages/getAllUsers.html.erb
<table class="table"> 
  <thead> 
  	<tr> 
  		<th>Email</th>
		<th>Admin?</th>
  	</tr> 
  </thead> 
  <tbody> 
  	<tr> 
		<% @users.each do |user| %>
		<td><%= user.email %></td>
		
	</tr>
		<% end %>
  </tbody>

</table>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
  </div>
<% end %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label "Severity" %><br>
    <%= f.select :level, [["Low", 1], ["Medium", 2], ["High", 3]] %>
  </div>

  <div class="field">
    <%= f.label :assigned_to %><br>
    <%= f.collection_select(:assigned_to, User.where("admin = ?", "true"), :id, :name, :prompt => 'Select') %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<% if @tickets.nil? %>

<% else %>
	<table class="table">
	  <thead>
	    <tr>
	      <th>Title</th>
	      <th>Body</th>
	      <th>Level</th>
	      <th>Assigned To</th>
	      <th>Created By</th>
	      <th colspan="3"></th>
	      <th>Resolved?</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @tickets.each do |ticket| %>
	      <tr>
		<td><%= ticket.title %></td>
		<td><%= ticket.body %></td>
		<td><%= ticket.level %></td>
		<% if ticket.user == nil %>
			<td><%= %></td>
		<% else %>
			<td><%= ticket.user.name %></td>
		<% end %>		
		<td><%= link_to 'Show', ticket %></td>
		<td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
		<td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% if current_user.admin? %>
			<td><%= best_in_place ticket, :status, as: :select, :collection => {"f" => "False", "t" => "True" }, :selected => "False" %>
		<% end %>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	<br>
<% end %>

<% if !current_user.admin? %>
	<%= link_to 'New Ticket', new_ticket_path %>
<% end %>

app/views/tickets/new.html.erb
<%= javascript_include_tag "tickets.js" %>

<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @ticket.body %>
</p>

<p>
  <strong>Severity:</strong>
  <%= @ticket.level %>
</p>

<p>
  <strong>Ticket Owner:</strong>
  <%= @ticket.user.name %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>